
@api = http://localhost:3000/Paciente
###Mostrar toda la tabla de pacientes
GET {{api}}
###Aniadir un nuevo paciente
POST {{api}}
Content-Type: application/json

{
    "ID_Paciente" : "6",
    "Nombre" : "Adrian",
    "Apellido" : "Rojas",
    "Genero" : "M",
    "Fecha_Nacimiento" : "2003-11-23",
    "Direccion" : "Tiqui",
    "Telefono" : "34372",
    "Correo_Electronico" : "Adri@gmail.com",
    "ID_Aseguradora" : "4" 
}

###Search de un paciente segun el ID que ingrese
GET {{api}}/3

###Delete un paciente segun el ID que le pasemos
DELETE {{api}}/1

### get Total Pacientes
GET {{api}}/count

###update Patient by ID
PUT {{api}}/2

Content-Type: application/json

{
    "ID_Paciente" : "2",
    "Nombre" : "Douglas",
    "Apellido" : "Padilla",
    "Genero" : "M",
    "Fecha_Nacimiento" : "2003-10-14",
    "Direccion" : "Sacaba",
    "Telefono" : "324234",
    "Correo_Electronico" : "Cami@gmail.com",
    "ID_Aseguradora" : "4" 
}